application: fotosop
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: bootstrap/css

- url: /js
  static_dir: bootstrap/js

- url: /fonts
  static_dir: bootstrap/fonts

- url: /images
  static_dir: images

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: numpy
  version: latest
- name: PIL
  version: latest
